### ISSUE TITLE
Keeping graph structure in GPU memory

### ISSUE THREAD

**Issue by tkelman** [tkelman/gunrock#1]
cc @ranjanan let's leave this as a placeholder for discussion, I'll have a serious look at this probably around Sunday

**Comment by ranjanan** [comment]
Bump! So Tony, we need to wrap [this](https://github.com/tkelman/gunrock/blob/master/gunrock/util/array_utils.cuh#L44) in Julia, and store `colval` and `rowptr` of the CSR in GPU Memory, and tweak the routines in the BFS to take our (new) graph object as input. 

cc @ViralBShah
